### ISSUE TITLE
[Bug] local variable 'lm_stats' referenced before assignment

### ISSUE THREAD

**Issue by danielinux7** [bitextor/bicleaner-ai#17]
I am getting an error message at the end of training a full model, here is a code snippet.

`File "/opt/conda/lib/python3.7/site-packages/bicleaner_ai/bicleaner_ai_train.py", line 217, in perform_training
27864.4s	121	    write_metadata(args, classifier, y_true, y_pred, lm_stats)
27864.4s	122	UnboundLocalError: local variable 'lm_stats' referenced before assignment`

Please let me know if there is a need to further clarify the steps to reproduce the error.

**Comment by ZJaume** [comment]
This is a bug in the latest release that is fixed in master. Unfortunately, master has some issues that I'm working with and may not be stable. You can do two things if you don't want to use master or if it fails for you:

- Clone the `v1.0.1` tag and apply [this](https://github.com/bitextor/bicleaner-ai/commit/7732f95f48d6856c9277dcf5282595277cc3d48c) change.
- Or train the bicleaner model with the lm_filter addint these options:
```
--lm_file_sl models/SRC-TRG/lm.SRC
--lm_file_tl models/TRG-TRG/lm.TRG
```
In this case, if you don't want to use `bicleaner-ai-classify` with the language model, you just need to run it with `--disable_lm_filter`. My advice is, if you are filtering small data, to not use it as it could filter out good sentences sometimes.

**Comment by ZJaume** [comment]
Closing this as it is fixed in master and will be released soon.
